"""General hierarchy helpers for Northern Expedition."""

from .general_tree import (
    DEFAULT_FORCE_POINTS,
    BODY_GUARD_LEVELS,
    add_loyalty,
    add_skill,
    add_trait,
    allocate_troops,
    calculate_force_strength,
    defect_general,
    increase_affiliation_slots,
    kill_general,
    loyalty_report,
    record_battle_loss,
    recruit_general,
    set_body_guard_level,
    subtree_force_strength,
    transfer_troops_between_absolute_loyal_pair,
    validate_tree,
)

__all__ = [
    "DEFAULT_FORCE_POINTS",
    "BODY_GUARD_LEVELS",
    "add_loyalty",
    "add_skill",
    "add_trait",
    "allocate_troops",
    "calculate_force_strength",
    "defect_general",
    "increase_affiliation_slots",
    "kill_general",
    "loyalty_report",
    "record_battle_loss",
    "recruit_general",
    "set_body_guard_level",
    "subtree_force_strength",
    "transfer_troops_between_absolute_loyal_pair",
    "validate_tree",
]
